### ISSUE TITLE
Add an option to the csv function to neither return nor print anything

### ISSUE THREAD

**Issue by choroba** [Tux/Text-CSV_XS#13]
Let's say I just want to populate a structure in `after_parse` or `on_in`, but I don't want to get the whole structure back, and I don't want to print it. E.g. I might want to accumulate information by id:
``` perl
csv (in      => shift,
     headers => "skip",
     on_in   => sub {
         my ($id, $email) = @{ $_[1] };
         push @{ $by_id{$id}{email} }, $email;
         },
    );
``` 
I'm only interested in %by_id. Something like `out => undef` or similar.

**Comment by Tux** [comment]
I needed that often too, and worked around that by just assigning it to an unused scalar
``` perl
my $void = (in => shift, on_in => sub { ...});
```
Due to internal implementation, I'm not keen on using undef. Would
``` perl
csv (in    => shift,
     out   => \undef,
     on_in => sub {
         push @{$by_id{$_[1][0]}{email}}, $_[1][1];
         },
    );
```
work for you too?

**Comment by choroba** [comment]
Yes, thanks a lot, `\'skip'` is nice, especially as it's something already present elsewhere. I assigned it to a variable, too, but it wasted the memory when the file was large, while the structure being collected was much smaller.

**Comment by Tux** [comment]
Consider it "patch applied" then. It will be in the next release. Feel free to fetch and test from github.
As always, thanks for the feedback. Will close this issue now.
