### ISSUE TITLE
csv2xls does not like (nearly) empty files

### ISSUE THREAD

**Issue by 0-wiz-0** [Tux/Text-CSV_XS#18]
When run on an empty file or one consisting only of whitespace, csv2xls throws some errors:
````
Use of uninitialized value $sep in string eq at csv2xls line 132.
Use of uninitialized value $sep in string ne at .../perl-5.16.2/lib/perl5/site_perl/5.16.2/x86_64-linux/Text/CSV_XS.pm line 135.
# CSV_XS ERROR: 1008 - INI - SEP undefined @ rec 0 pos 0
Can't call method "getline" on an undefined value at /grasp_mob_c/local/bin/csv2xls line 163.
````
It would be nice if it would just output an empty file, or one with a cell containing the whitespace.

**Comment by Tux** [comment]
pull. Like [this](https://github.com/Tux/Text-CSV_XS/commit/1d6edfd480a02b24d493e07c821dd4ee06622b8d)?

**Comment by 0-wiz-0** [comment]
@Tux Thanks for the quick patch.
Yes, like that; or generate an empty output file.

**Comment by Tux** [comment]
It'll be in the next release. That'll have to wait a bit, as I am working on stackable encodings
