### ISSUE TITLE
Calling $csv->header breaks auto_diag in 1.40

### ISSUE THREAD

**Issue by afresh1** [Tux/Text-CSV_XS#19]
In this short test script, I expect a "CSV_XS ERROR: 2023 - EIQ - QUO character not allowed @ rec 2 pos 6 field 2" exception in the loop, and that happens if the line calling `$csv->header` is commented out.  However, after calling `->header` it seems `Text::CSV_XS::error_diag` is getting called with no arguments and so `$self` is falsy and so the `croak` is never triggered.  Instead we fall through to the "why no auto_diag" exception.

```perl
#!/usr/bin/perl
use strict;
use warnings;
use Text::CSV_XS;

my $csv = Text::CSV_XS->new( { auto_diag => 2 } );
$csv->header(*DATA); # comment out this line to hide the bug
while ( my $row = $csv->getline(*DATA) ) { print "$row->[0]\n" }
die "why no auto_diag for: " . $csv->error_diag
    if $csv->error_diag and $csv->error_diag != 2012;

__DATA__
Foo,Bar,Baz
a,xxx,1
b,"xx"xx", 2
c, foo , 3
```

**Comment by Tux** [comment]
It might help to tell which version of perl on what OS and which version of Text::CSV_XS you are using, as I get 2023 (as expected) for both:
```
#!/pro/bin/perl

use 5.16.2;
use warnings;

use Text::CSV_XS;

binmode STDOUT, ":encoding(utf-8)";
binmode STDERR, ":encoding(utf-8)";

my $h = shift // 0;

sub show {
    say join ", " => map { "\x{231e}$_\x{231d}" } @_;
    } # show

my $csv = Text::CSV_XS->new ({ auto_diag => 2 });
if ($h) {
    say "Calling header";
    show ($csv->header (*DATA)); # comment out this line to hide the bug
    }
while (my $row = $csv->getline (*DATA)) {
    show (@$row);
    }
$csv->error_diag;
say "EOF: ", $csv->eof ? "Yes" : "No";

__DATA__
Foo,Bar,Baz
a,xxx,1
b,"xx"xx", 2
c, foo , 3
```
```
$ perl 2012-2023.pl 0
⌞Foo⌝, ⌞Bar⌝, ⌞Baz⌝
⌞a⌝, ⌞xxx⌝, ⌞1⌝
# CSV_XS ERROR: 2023 - EIQ - QUO character not allowed @ rec 2 pos 6 field 2
Exit 2
$ perl 2012-2023.pl 1
Calling header
⌞foo⌝, ⌞bar⌝, ⌞baz⌝
⌞a⌝, ⌞xxx⌝, ⌞1⌝
# CSV_XS ERROR: 2023 - EIQ - QUO character not allowed @ rec 3 pos 6 field 2
Exit 2
```

**Comment by afresh1** [comment]
I apologize, I should have included OS and perl version information, although it doesn't seem to make a difference.  I did say 1.40 in the description, but wasn't clear that was Text::CSV_XS 1.40.  I tested it against the latest release of each even version of perl from 5.10 through 5.30 and on perl 5.31 all with the same results.  This was both on linux and OpenBSD.

**Comment by Tux** [comment]
I can reproduce, and I will look into it. $work interferes though

**Comment by Tux** [comment]
@afresh1 can you pull and try? I think I fixed it.
I still need to write a reproducable test case before I can release

**Comment by afresh1** [comment]
That does seem to work the way I expect, thank you!

**Comment by Tux** [comment]
@afresh1 any feedback?

**Comment by afresh1** [comment]
Feedback beyond the fix seems to be good?  I am not sure what feedback you are asking for.

**Comment by Tux** [comment]
/me missed that you closed it. sorry.
