### ISSUE TITLE
csv munge_column_names function fails with sep=; header

### ISSUE THREAD

**Issue by francoisbeaulieu** [Tux/Text-CSV_XS#23]
Hi,

I'm attempting to use the 'csv' function of Text::CSV_XS with munge_column_names set to "db". This fails when the .csv file passed to the script starts with the sep=; line to indicate the field separator, with the following error message:

# CSV_XS ERROR: 1012 - INI - the header contains an empty field @ rec 1 pos 0

Setting sep_set to 1 doesn't seem to make a difference but it all works correctly when I manually remove the sep=; line from the .csv file. Reading the documentation, I was under the impression that the 'sep=' feature was implemented in version 1.17.  I am missing a detail to get this to work?

I am running Text::CSV_XS version 1.41 built from MacPorts on Perl v5.26.3 (Mac OS X 10.13.6)

**Comment by Tux** [comment]
Thanks for reporting
Fixed in https://github.com/Tux/Text-CSV_XS/commit/d4b88d8ebef72a8fcd7609267857a47291fe169c
