### ISSUE TITLE
getter quote_char() and escape_char() returning 0 instead of undef

### ISSUE THREAD

**Issue by XSven** [Tux/Text-CSV_XS#24]
I have created a csv object with a no-arg constructor call. I have set the quote character and the escape character to the undef value 

```
my $csv = Text::CSV_XS->new;
$csv->quote_char (undef);
$csv->escape_char(undef);
```
Instead of undef the quote_char and escape_char getters return 0. That means I am not able to use the getters to pass this information to a DBI:CSV connect() call?! 

```
$dbh = DBI->connect ("DBI:CSV:", undef, undef, {
  ...
  csv_quote_char  => $csv->quote_char,
  csv_escape_char => $csv->escape_char,
  ...
```

**Comment by Tux** [comment]
Does https://github.com/Tux/Text-CSV_XS/commit/cd6afdc0fe61117b8f5d2e403a8538fc60e5ae42 fix it for you?

**Comment by XSven** [comment]
Yes thanks perfect. Maybe you should add 2 extra unit tests before your quote_char tests.
```
is ($csv->escape_char (undef), undef, "escape_char (undef)");
is ($csv->{escape_char}, undef, "{escape_char} (undef)");
```
How is your schedule to upload this new release to CPAN?

**Comment by Tux** [comment]
Those are not needed as the fix is in shared code. OTOH it wouldn't harm to add them anyway.
There was no plan yet, as I just released a version recently, but if it helps you, I'll start a test/release cycle. (such a cycle normally takes a whole day, as I test against 200+ versions of perl and on ± 20 OS variants).

**Comment by XSven** [comment]
I would appreciate, if you could start the test/release cycle. Thank you.

**Comment by Tux** [comment]
1.43 just sent to CPAN. Closing
