### ISSUE TITLE
Can't parse fields with nested quotes and commas

### ISSUE THREAD

**Issue by akastrin** [Tux/Text-CSV_XS#31]
I have the following line in my CSV file:
`nj23h32n,"By using "pseudoenergies", we were able to design multiple peptide sequences that showed low micromolar viral entry inhibitory activity.",2010-06-22,`

The 2nd field is the "abstract" field which could contain double quotes and commas as in the example above. I use the following one-liner to parse the file:
`perl -MText::CSV_XS=csv -wE'csv(in=>csv(in=>"test.csv",sep=>",",allow_loose_quotes=>1,allow_loose_escapes=>1))'`

But I get:
`nj23h32n,"By using ""pseudoenergies"," we were able to design multiple peptide sequences that showed low micromolar viral entry inhibitory activity.""",2010-06-22,`

Any idea how to correctly parse this example?

Thanks in advance,
Andrej

**Comment by Tux** [comment]
I see only one solution: **fix the generator**.
The workaround will be unreliable. If it allways is the second field the is problematic, you might be able to make a reconstructor on the resulting record if it does not contain exaclty 4 fields, but I sincerely wonder if that would be possible.

**Comment by akastrin** [comment]
Thanks. I will close the issue.
