### ISSUE TITLE
 Offer option to not put empty columns into hashes created

### ISSUE THREAD

**Issue by jidanni** [Tux/Text-CSV_XS#32]
Please see https://github.com/makamaka/Text-CSV/issues/48 .
I don't know how to reassign this bug to here.

**Comment by Tux** [comment]
Closing without a change:

I don't see enough value in documenting this, as (imho) this is not something that many people are looking for and it would require relatively big chunks of text to explain (compared to other recipes). As I already got complaints that the docs are too big, I'll leave it as it is.
Another consideration is that many value speed over size, and filtering empty columns/fields to preserve memory will slow down considerably. Of course you can run benchmarks and decide for yourself.
If memory is really an issue, rewrite your code to stream and process without storing all of the data (`getline` or `csv (out => undef, …)`
