### ISSUE TITLE
Procedure (or method) returning the error text

### ISSUE THREAD

**Issue by arnesom** [Tux/Text-CSV_XS#33]
As the error codes are not very end-user  friendly.

Either as a method (to be used instead of `$csv->error_diag`) or as a procedure wrapper (e.g.` textual_error($csv->error_diag)`.

**Comment by Tux** [comment]
From the docs:
```
   error_diag
        Text::CSV_XS->error_diag ();
        $csv->error_diag ();
        $error_code               = 0  + $csv->error_diag ();
        $error_str                = "" . $csv->error_diag ();
        ($cde, $str, $pos, $rec, $fld) = $csv->error_diag ();
```
Do you now ask to make a *new* method to mimic the behavior of <c>"".$csv->error_diag`?

**Comment by arnesom** [comment]
Ah. I missed that section, and read "Diagnostics". 
Then I have what I need. Thank you for the help.
