### ISSUE TITLE
getline_all does not understand scientific ("e") notation

### ISSUE THREAD

**Issue by vividsnow** [Tux/Text-CSV_XS#39]
Hello

Consider input file with 1 billion records:

`my $batch = $csv->getline_all ($fh,  0, 1e6)` will return all data
`my $batch = $csv->getline_all ($fh,  0, 1000000)` will return 1000000 recs

**Comment by Tux** [comment]
Thanks for the report. Fixed in 9d094d212382bc36702b73

**Comment by vividsnow** [comment]
Thank you!
