### ISSUE TITLE
BOM without a header line.

### ISSUE THREAD

**Issue by charsbar** [Tux/Text-CSV_XS#40]
re: https://github.com/makamaka/Text-CSV/issues/61

> [yewtc](https://github.com/yewtc) commented [19 hours ago](https://github.com/makamaka/Text-CSV/issues/61#issue-1413221868)
The option detect_bom is only available in the header method, but not all CSVs have header lines. The detect_bom functionality should be used on the first line of the file, not just the header line.

**Comment by charsbar** [comment]
That makes sense to me. Thanks.

**Comment by remorse** [comment]
I'm afraid I don't quite understand "the header method can be called with a lot of options/arguments, making it effectively a method to just deal with byte order marks and ignore the header" — how do set the headers option without having it interpret the first line as a header line?

I have a bunch of CSV files that I get that have a BOM in them. I want to process them without treating the first line as headers. Would it be possible to add some parameter to the `csv` function so I could tell the module there is a BOM and it should be ignored? Right now, I have to open them in my text editor and change the format to suppress the BOM, which gets tiresome...

Thanks,
Ricky

**Comment by Tux** [comment]
If I understand your case correctly, then what you "missed" in the documentation is the option/attribute `set_column_names`.

```
my $aoh = csv (in => "file.csv", bom => 1);     # Array of Hashes
my $aoa = csv (in => "file.csv", bom => 1, set_column_names => 0); # Array of Arrays
```
 As shown by demo-script below.
```
#!/pro/bin/perl

use 5.014002;
use warnings;

our $VERSION = "0.01 - 20230122";
our $CMD = $0 =~ s{.*/}{}r;

sub usage {
    my $err = shift and select STDERR;
    say "usage: $CMD ...";
    exit $err;
    } # usage

use Data::Peek;
use Text::CSV_XS qw( csv            );
use Getopt::Long qw(:config bundling);
GetOptions (
    "help|?"            => sub { usage (0); },
    "V|version"         => sub { say "$CMD [$VERSION]"; exit 0; },

    "v|verbose:1"       => \(my $opt_v = 0),
    ) or usage (1);

my $fn = "BOM-NH-$$.csv"; END { -f $fn and unlink $fn }

open my $fh, ">:encoding(utf-8)", $fn or die "$fn: $!\n";
say $fh "\N{BOM}foo,bar,baz";
say $fh "1,2,42";
close $fh;

DDumper csv (in => $fn, bom => 1);

DDumper csv (in => $fn, bom => 1, set_column_names => 0);
```

**Comment by remorse** [comment]
Thank you! That does exactly what I wanted.

Now reading the documentation for that, I'm confused how this should have been understood?

> If set_column_names is passed, the method "header" is invoked on the opened stream with all arguments meant for "header".

sounds like it's just an alias for `header` except that it isn't clear where the arguments "meant for `header`" come from?

> If set_column_names is passed as a false value, the content of the first row is only preserved if the output is AoA:

This sentence I don't understand because of the "if the output is AoA", which I thought was controlled by the `headers` option, which this interacts with strangely?

But I admit, I hadn't really seen it before, and in action it seems to do what I want.

Many thanks!

Ricky

**Comment by Tux** [comment]
If you are confused, that indicates that the docs show opportunities for improvement.

My native tongue is not English, so I am open to suggestions.

```
If set_column_names is passed, the method "header" is invoked on the opened stream with all arguments meant for "header".
```
All arguments allowed in the method `header` are also allowed in the function `csv` even when called as method. If any of the arguments accepted by the `header` method are passed as arguments to `csv`, the stream or file opened in `csv` is first subject to the `header` method with all recognized arguments.
If I read your comment again, I think that just changing that text to
```
If set_column_names is passed, the method "header" is invoked on the opened stream with all arguments meant for the "header" method.
```
would suffice.

With regard to the AoA note: if the first line is used as a header, it is seen as column names, and not as data. The output then is AoH.
