### ISSUE TITLE
improper reinitialization of $v_ref

### ISSUE THREAD

**Issue by XSven** [Tux/Text-CSV_XS#53]
Please have a look at the [Text-CSV-PR-68](https://github.com/makamaka/Text-CSV/pull/68).

**Comment by XSven** [comment]
Handled in https://github.com/makamaka/Text-CSV/pull/68

**Comment by XSven** [comment]
I was unable to reopen https://github.com/makamaka/Text-CSV/pull/68, therefore I have decided to reopen this issue.

**Comment by Tux** [comment]
Eventually fixed in 8cdf92eb01d687b8ceeaf1315cebd593f90ac682
