### ISSUE TITLE
need method to access the complete (unparsed) line

### ISSUE THREAD

**Issue by XSven** [Tux/Text-CSV_XS#55]
This is a clone of https://github.com/makamaka/Text-CSV/issues/66. The workaround that is based on `$csv->{ _CACHE }->{ tmp }` does not work for the XS backend Text-CSV_XS. Could you offer something official/public?!

**Comment by Tux** [comment]
No.

In any case not for getline (). There is `$csv->{_STRING}` when you use `$csv->parse ()`, but in that case then end-user is responsible for dealing with line separation. And `->{_STRING}` isn't documented for a reason: it should neven be reliad upon.

There are no plans to change this, as it is a serious slowdown and needs additional bookkeeping.

In your case `IO::Tee` might help.
