### ISSUE TITLE
Quotes in the middle of an unquoted field produce misleading error

### ISSUE THREAD

**Issue by knmiecc** [Tux/Text-CSV_XS#56]
Version: 1.54

When I create a csv instance with strict => enabled, and the quote_char => '"' and escape_char => '"', for certain inputs I get a misleading error response on parsed strings. Consider the following example:

```
my $csv = Text::CSV_XS->new(
  {
    binary      => 1,
    comment_str => '#',
    eol         => "\n",
    escape_char => '"',
    quote_char  => '"',
    sep_char    => '|',
    strict      => 1,
  }
);

my $status = $csv->parse( 'a|b|"d"' );
note( ( 0 + $csv->error_diag ) . ' - ' . ( '"' . $csv->error_diag . '"' ) . "\n" ); # prints '0 - ', i.e. works fine
$status = $csv->parse( 'a|b|c"d"e' );
note( ( 0 + $csv->error_diag ) . ' - ' . ( '"' . $csv->error_diag . '"' ) . "\n" ); # prints '2014 - "ENF - Inconsistent number of fields"'
```

From my understanding Text::CSV_XS treats the occurrence of a quote character as the beginning of an entirely new field, ignoring that the previous character here was not the sep_char '|'.

This in my opinion is at least a very misleading error to print here, because on first glance the string 'a|b|c"d"e' has the exact right number of fields: 3. 
If, with strict => 1 and a quote_char set, quotes are only allowed at the beginning/end of a field but not in the middle, there should be a different error code/message signaling that an irregular quoting was detected.

**Comment by Tux** [comment]
I agree. I will have a look. `strict` proves to be more a pain-in-the-ass than I ever expected it to be

**Comment by Tux** [comment]
Fix pushed

**Comment by Tux** [comment]
Yes, I hope to be able to do a release this weekend. No promise though

**Comment by Tux** [comment]
FWIW, that other issue was already fixed :)

**Comment by Tux** [comment]
1.55 is out
