### ISSUE TITLE
comment_str is not honoured in strict mode

### ISSUE THREAD

**Issue by XSven** [Tux/Text-CSV_XS#57]
I don't understand why this exception is raised
```
# CSV_XS ERROR: 2014 - ENF - Inconsistent number of fields @ rec 2 pos 15
# some comment
              ^
```
when calling
```
use strict;
use warnings;

use Text::CSV_XS ();

my $csv = Text::CSV_XS->new ({
    strict       => 1,
    comment_str  => "#",
    sep_char     => "|",
    auto_diag    => 2,
    diag_verbose => 1,
    });

$csv->parse ('a|b');
$csv->parse ('# some comment');
```
From my perspective the comment string should be ignored and the last `parse()` call should not fail.

**Comment by Tux** [comment]
The explanation for the current release is easy: at this point it is unclear if it is EOF (end-of-file/end-of-data), which is one of the criteria to decide if this is to reported. If this would have been a stream, no warnings would have been issued

```
🐧 cat sandbox/issue-57.pl
use strict;
use warnings;

use Text::CSV_XS ();

my $csv = Text::CSV_XS->new ({
    strict       => 1,
    comment_str  => "#",
    sep_char     => "|",
    auto_diag    => 2,
    diag_verbose => 1,
    });

if (shift) {
    $csv->getline (*DATA);
    $csv->getline (*DATA);
    }
else {
    $csv->parse ("a|b");
    $csv->parse ("# some comment");
    }
__END__
a|b
# some comment
🐧 perl -Mblib sandbox/issue-57.pl
# CSV_XS ERROR: 2014 - ENF - Inconsistent number of fields @ rec 2 pos 15
# some comment
              ^
Exit 255
🐧 perl -Mblib sandbox/issue-57.pl 1
🐧
```
I'll see what I can do about that

**Comment by Tux** [comment]
Can you try 7636c50dd8192f4c022126e8c267db029c7c03f2 ?

And what would *you* expect as return? One empty field or no fields at all?

**Comment by XSven** [comment]
Parsing a comment should return no fields at all.

**Comment by XSven** [comment]
Thx. The commit works but I would suggest that `fields()` should return no fields at all.

**Comment by XSven** [comment]
There is another `strict` mode related issue/use case: If I set 3 `column_names()` in `strict` mode

`$csv->column_names( qw( A B C ) );`

and then `parse()` only 2

`$csv->parse ('a|b');`

I would expect an exception. Should I create a separate issue for that?

**Comment by Tux** [comment]
> Thx. The commit works but I would suggest that `fields()` should return no fields at all.

Check 8c08ecd27d6b1def928fa4b1138dfafa0794905d

**Comment by Tux** [comment]
Seperate issue please

**Comment by XSven** [comment]
Commit https://github.com/Tux/Text-CSV_XS/commit/8c08ecd27d6b1def928fa4b1138dfafa0794905d  is ok. Thx!
