### ISSUE TITLE
POD: Decide if it is $fh or $io

### ISSUE THREAD

**Issue by LadyAleena** [Tux/Text-CSV_XS#8]
In the POD, there are many usage examples. However, they flip between `$fh` and `$io`. `$fh` is used more often, so I would suggest turning all `$io` uses into `$fh`. Also, `$fh` is more widely used by the community in general when making a common variable for a file handle.

I could copy the POD and make the changes, but I don't know how to do a pull request. I could paste the edit here or elsewhere if you want me to do it.

Lady Aleena

**Comment by Tux** [comment]
done
