### ISSUE TITLE
skip empty or blank

### ISSUE THREAD

**Issue by LadyAleena** [Tux/Text-CSV_XS#9]
If a field is empty or blank, it would be nice if if could be skipped completely not made `undef`. So how about `skip_empty` and `skip_blank`?

(I was going to try to see if I could write this based on `blank_is_undef` and `empty_is_undef`, but I could not figure out how those interact with the method or function.)

**Comment by Tux** [comment]
• That would completely break if using hashes (using headers)
```
  a,b,c,d
  1,2,3,4
  6,,7,8
```
In the second row, $_->{c} would be 8 and $_->{d} would be undef or  - with bind_columns - 4

• easy to do on lists
``` perl
  my $aoa = csv (in => $file, on_in => sub { @{$_[1]} = grep { length } @{$_[1]} });
```
I understand your quest, but I think that an option like that would
cause more obfuscation that it would address

**Comment by Tux** [comment]
As no counterargument has been posted, closing this discussion/issue
